arch: PipelineB_Unet
batch_size: 1
com: null
debug: false
deep_sup: false
devices: 0,1
dropout: 0.1
epochs: 100
exp_name: PipelineB_20251004_160405__fold0_PipelineB_Unet_64_batch1_optimadamw_lr8e-05-wd0.0001_epochs100_deepsupFalse_fp16_warm5__normgroup_dropout0.1_warm_restartFalse
fold: 0
fold_seed: 222
full: false
lr: 8.0e-05
no_fp16: false
norm_layer: group
optim: adamw
pipeline: B
resume: /kaggle/input/pipelineb-model-epoch40/model_last.pth.tar
seed: '42'
start_epoch: 0
swa: false
swa_repeat: 7
val: 3
warm: 5
warm_restart: false
weight_decay: 0.0001
width: 64
workers: 2
