arch: Unet
batch_size: 1
com: null
debug: false
deep_sup: true
devices: 0,1
dropout: 0.0
epochs: 100
exp_name: PipelineA_20251003_140611__fold0_Unet_48_batch1_optimranger_lr0.0001-wd0.0_epochs100_deepsupTrue_fp16_warm0__normgroup_swa5_dropout0.0_warm_restartFalse
fold: 0
fold_seed: 111
full: false
lr: 0.0001
no_fp16: false
norm_layer: group
optim: ranger
pipeline: A
resume: ''
seed: '42'
start_epoch: 0
swa: true
swa_repeat: 5
val: 3
warm: 0
warm_restart: false
weight_decay: 0.0
width: 48
workers: 2
